# This is a basic workflow to help you get started with Actions

name: Package

# Controls when the workflow will run
on:
  
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create Package
        uses: BigWigsMods/packager@master
        env:
      # This section might already create other env variables, just append the WAGO_API_TOKEN to these
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }} 
          
